# Generated by Django 5.2.5 on 2026-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIFaculty",
            fields=[
                ("msuis_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(blank=True, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIPaper",
            fields=[
                ("msuis_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("paper_name", models.CharField(max_length=500)),
                ("paper_code", models.CharField(max_length=100)),
                ("raw_payload", models.JSONField(default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIStudent",
            fields=[
                ("prn", models.BigIntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email_id", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIStudentAcademicInformation",
            fields=[
                ("msuis_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("prn", models.BigIntegerField(db_index=True)),
                ("student_admission_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "programme_instance_part_term_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("programme_id", models.BigIntegerField(blank=True, null=True)),
                ("specialisation_id", models.BigIntegerField(blank=True, null=True)),
                ("academic_year_id", models.BigIntegerField(blank=True, null=True)),
                ("institute_id", models.BigIntegerField(blank=True, null=True)),
                ("faculty_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "part_term_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIStudentPartTermPaperMap",
            fields=[
                ("msuis_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("prn", models.BigIntegerField(blank=True, db_index=True, null=True)),
                (
                    "student_academic_information_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "programme_instance_part_term_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("paper_id", models.BigIntegerField(blank=True, null=True)),
                ("mst_paper_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "obtained_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "obtained_grade",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "paper_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "part_term_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("division", models.CharField(blank=True, max_length=20, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prn", models.BigIntegerField(db_index=True)),
                ("subject_code", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("division", models.CharField(max_length=20)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("prn", "subject_code", "division", "year")},
            },
        ),
    ]
