# Generated by Django 5.2.5 on 2026-05-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DatabaseAdminApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apienrollment",
            name="department_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="apienrollment",
            name="program_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="apienrollment",
            name="raw_payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="apienrollment",
            name="semester",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
