# Generated by Django 5.2.5 on 2026-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DatabaseAdminApp", "0002_apienrollment_department_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apienrollment",
            name="department_name",
        ),
        migrations.RemoveField(
            model_name="apienrollment",
            name="program_name",
        ),
        migrations.RemoveField(
            model_name="apienrollment",
            name="raw_payload",
        ),
        migrations.RemoveField(
            model_name="apienrollment",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="apienrollment",
            name="synced_at",
        ),
        migrations.RemoveField(
            model_name="apifaculty",
            name="synced_at",
        ),
        migrations.RemoveField(
            model_name="apipaper",
            name="synced_at",
        ),
        migrations.RemoveField(
            model_name="apistudent",
            name="synced_at",
        ),
        migrations.RemoveField(
            model_name="apistudentacademicinformation",
            name="synced_at",
        ),
        migrations.RemoveField(
            model_name="apistudentparttermpapermap",
            name="synced_at",
        ),
        migrations.AlterField(
            model_name="apienrollment",
            name="prn",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="apifaculty",
            name="raw_payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="apipaper",
            name="raw_payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="apistudent",
            name="raw_payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="apistudentacademicinformation",
            name="raw_payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="apistudentparttermpapermap",
            name="raw_payload",
            field=models.JSONField(),
        ),
    ]
