# Generated by Django 5.2.5 on 2026-05-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DatabaseAdminApp", "0003_remove_apienrollment_department_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIFaculty",
        ),
        migrations.DeleteModel(
            name="APIStudentAcademicInformation",
        ),
        migrations.DeleteModel(
            name="APIStudentPartTermPaperMap",
        ),
    ]
