# Generated by Django 5.2.5 on 2026-07-16 17:07

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('class_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the holiday.', unique=True)),
                ('name', models.CharField(help_text='e.g., Diwali, Independence Day, Heavy Rain', max_length=255)),
                ('is_working_day', models.BooleanField(default=False, help_text="Check if attendance is still required despite being a 'holiday'.")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='', unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='attendance_photos/')),
                ('detected_photo', models.ImageField(blank=True, null=True, upload_to='detected_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Home.classsession')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
            options={
                'unique_together': {('department', 'year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.BigIntegerField(unique=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('face_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('notification_token', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.division')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendancePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_count', models.IntegerField(default=0)),
                ('attendancePercentage', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField(null=True)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('notification_token', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
        ),
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('ui_order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.division')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
                ('proxy_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_daily_sessions', to='Home.teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher'),
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday')),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('ui_order', models.PositiveIntegerField(default=0)),
                ('default_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.division')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
            ],
            options={
                'unique_together': {('class_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_prn', models.BigIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
            ],
            options={
                'unique_together': {('student_prn', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectFromDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
                ('subject', models.ManyToManyField(to='Home.subject')),
            ],
            options={
                'unique_together': {('department', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.division')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher')),
            ],
            options={
                'unique_together': {('teacher_id', 'subject', 'division')},
            },
        ),
    ]
